-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 16:30:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paiza_learn_track
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paiza_learn_track
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paiza_learn_track` DEFAULT CHARACTER SET utf8 ;
USE `paiza_learn_track` ;

-- -----------------------------------------------------
-- Table `paiza_learn_track`.`team_user_task_progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paiza_learn_track`.`team_user_task_progress` (
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`email_address` VARCHAR(256) NOT NULL COMMENT 'メールアドレス',
	`course_id` INT NOT NULL COMMENT '講座ID',
	`course_name` VARCHAR(128) NOT NULL COMMENT '講座名',
	`course_completion_flag` VARCHAR(32) NOT NULL COMMENT '講座完了フラグ',
	`lesson_id` VARCHAR(128) NOT NULL COMMENT 'レッスンID',
	`lesson_name` VARCHAR(128) NOT NULL COMMENT 'レッスン名',
	`lesson_completion_flag` VARCHAR(32) NOT NULL COMMENT 'レッスン完了フラグ',
	`chapter_id` INT NOT NULL COMMENT 'チャプターID',
	`chapter_name` VARCHAR(128) NOT NULL COMMENT 'チャプター名',
	`chapter_completion_flag` VARCHAR(32) NOT NULL COMMENT 'チャプター完了フラグ',
	`chapter_start_datetime` DATETIME NOT NULL COMMENT 'チャプター受講開始日時',
	`chapter_last_access_datetime` DATETIME NOT NULL COMMENT 'チャプター最終受講日時',
	`created` DATETIME NOT NULL COMMENT '作成日時',
	`updated` DATETIME NOT NULL COMMENT '更新日時',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'チームユーザー課題進捗';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
